library(gsubfn)
library(DBI)
library(proto)
library(RSQLite)
library(sqldf)
library(tcltk)
df <- read.csv2.sql("household_power_consumption.txt", sql = "select * from file where Date in ('1/2/2007', '2/2/2007')", header = TRUE, sep = ";")  
datetime   <- as.POSIXlt(paste(as.Date(df$Date, format="%d/%m/%Y"), df$Time, sep=" "))
png(filename = "plot2.png", width = 480, height = 480)
plot(datetime, df$Global_active_power, type = "l", xlab = " ", ylab = "Global Active Power (kilowatts)")
dev.off()
