library(gsubfn)
library(DBI)
library(proto)
library(RSQLite)
library(sqldf)
library(tcltk)
df <- read.csv2.sql("household_power_consumption.txt", sql = "select * from file where Date in ('1/2/2007', '2/2/2007')", header = TRUE, sep = ";")  
datetime   <- as.POSIXlt(paste(as.Date(df$Date, format="%d/%m/%Y"), df$Time, sep=" "))
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow = c(2, 2))
with(df, {
  plot(datetime, df$Global_active_power, type = "l", xlab = " ", ylab = "Global Active Power")
  plot(datetime, df$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
  plot(datetime, df$Sub_metering_1, col = "Black", type = "l", xlab = " ", ylab = "Energy sub metering")
  points(datetime, df$Sub_metering_2, col = "Red", type = "l")
  points(datetime, df$Sub_metering_3, col = "Blue", type = "l")
  legend("topright", lty =  1, col = c("Black", "Red", "Blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n")
  plot(datetime, df$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
})
dev.off()
